= Согласования при создании заказа
:toc-title: Оглавление
:toc:

== Usecase

Менеджер КЛО имеет возможность при создании заказа "До Маркетплейса" в ЭК5 (то есть до его реального создания) сразу проставлять согласование на допустимую дату и интервал, поскольку склады маркетплейсов принимают груз только в определенные дни недели и время, при нарушении которых выставляются штрафы нашим клиентам.

Таким образом, предоставляется возможность выбора ближайшей даты и интервала согласования на этапе создания заказа

== Получение интервалов по параметрам заказа


[plantuml,format="png"]
----

!define RECTANGLE class

title Микросервисная архитектура для "Создание заказа по доставке по ссылке"

RECTANGLE AuthService {
    AuthService -- OrderService : <<authenticate>>
}

RECTANGLE ProductService {
    ProductService -- OrderService : <<getProductInfo>>
}

RECTANGLE InventoryService {
    InventoryService -- OrderService : <<checkStock>>
}

RECTANGLE DeliveryService {
    DeliveryService -- OrderService : <<calculateDeliveryCost>>
}

RECTANGLE BillingService {
    BillingService -- OrderService : <<calculateTotalCost>>
}

RECTANGLE PaymentService {
    PaymentService -- OrderService : <<processPayment>>
}

RECTANGLE ReviewService {
    ReviewService -- OrderService : <<manageReviews>>
}

RECTANGLE OrderHistoryService {
    OrderHistoryService -- OrderService : <<saveOrderHistory>>
}

RECTANGLE OrderService {
    OrderService -- BillingService : <<calculateTotalCost>>
}

AuthService ..> OrderService : <<checkUserAuth>>
ProductService ..> OrderService : <<getProductDetails>>
InventoryService ..> OrderService : <<checkInventory>>
DeliveryService ..> OrderService : <<getDeliveryOptions>>
PaymentService ..> OrderService : <<processPayment>>


----

== Пример Request

    {
        "cityOfDepartureUuid": "c7d193aa-2716-452a-ac09-ea37dc2b3328",
        "officeOfDepartureUuid": "c7d193aa-2716-452a-ac09-ea37dc2b3328",
        "cityOfDeliveryUuid": "c7d193aa-2716-452a-ac09-ea37dc2b3328",
        "address": "ул. Большевистская, 101, БЦ Рим",
        "deliveryDateTime": "2024-01-01T18:23:00",
        "tariffId": "450",
        "speedTypeCode": "2",
        "additionalOrderType": [1, 2, 3]
    }
